language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
sudo: required
services:
  - docker

before_install:
  - docker build -t cuckoo/frontend -f Deockerfile.dev .

script:
  - docker run cuckoo/frontend npm run test