sudo: required
services:
  - docker

before_install:
  - docker build -t cuckoo/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true cuckoo/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region:  "ap-south-1"
  app: "docker-workflow"
  env: "DockerWorkflow-env"
  bucket_name: "elasticbeanstalk-ap-south-1-287408872399"
  bucket_path: "docker-workflow"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
      secure: "$AWS_SECRET_KEY"